### ISSUE TITLE
Immersive touch not working anymore.

### ISSUE THREAD

**Issue by MrDomino4195** [ImTiara/VRCMods#10]
Hello, I'm not too sure what the issue is but recently the ImmersiveTouch mod stopped working, I'm not getting any errors just warnings when I enable the mod.
[ImmersiveTouch] [WARNING] Failed Capability Result: Invalid avatar animator.
This worked before and on the same avatar, I tried it on others aswell and it didn't work.
![voicemeeterpro_gJwLiTLZTP](https://user-images.githubusercontent.com/106647734/171334414-90326c63-3b55-44dc-b80a-bcdad0d197cc.png)
I also have Multiplayer Dynamic Bones.

**Comment by LunarstarFurry** [comment]
Same

**Comment by ImTiara** [comment]
A fix will be published very soon
