### ISSUE TITLE
Immersive Touch not working

### ISSUE THREAD

**Issue by nyowdy** [ImTiara/VRCMods#12]
Hey! On my avatar, immersive touch hasn't been working anymore since the physbones update. I have dynamic bone colliders on both hands, so maybe that is the problem?

It still works on other avatars, but I'm wondering what I need to do for it to work on my avatar. Thanks!

**Comment by ImTiara** [comment]
Hi, which version of ImmersiveTouch are you on?

**Comment by nyowdy** [comment]
2.0.1

**Comment by ImTiara** [comment]
Check your console for messages, try another avatar and see if it works.

**Comment by nyowdy** [comment]
falls to my knees IT SAID I DIDNT HAVE THE MIDDLE DISTAL FINGER BONE IM SO SORRY FOR BOTHERING U TYSM BWAHAHAHA

**Comment by ImTiara** [comment]
All good:)
