### ISSUE TITLE
Immersive Touch, cannot use this avatar, missing distal bones

### ISSUE THREAD

**Issue by adamwonn** [ImTiara/VRCMods#13]
Hello, ImmersiveTouch does not work on one of my avatars (Kepler v2). In the log, it says:
` [WARNING] Immersive Touch cannot use this avatar because the Left/Right Middle Distal finger bone are missing.`

My avatar does have those bones:
![image](https://user-images.githubusercontent.com/70366667/179368311-a3becc6d-377f-40bf-8615-b3264cb0c586.png)

I'm not super familiar with Unity and stuff like that, so maybe it's just a simple missing assignment of some kind?

I am using:
SDK3 2022.06.03
VRChat 2022.2.1p6-1207--Release
MelonLoader v0.5.4 Open-Beta
Windows 10

Mods:
```
ActionMenuApi v0.3.5
ImmersiveTouch v2.0.2
ReModCE v1.0.0.6
UI Expansion Kit v1.0.2
VRChatUtilityKit v1.5.0
```

**Comment by ImTiara** [comment]
Hi.
Most likely the hand of the avatar hasn't been mapped correctly. To solve this, follow these steps:
1. Select your FBX in unity.
2. Under the "Rig" tab, click the "Configure" button.
3. Start by selecting "Left Hand"
Make sure that your avatar's hand is mapped according to the image or as close as possible to it.
![image](https://user-images.githubusercontent.com/39366953/179370462-d94e54d0-9234-4d29-8a7f-b90529ab86c0.png)
Do the same for Right Hand.

ImmersiveTouch uses some of your fingers to determine the optimal collision position & size.

Hope this helps.

**Comment by adamwonn** [comment]
That was it. I'm glad it was something simple like that. Thank you!
