### ISSUE TITLE
Not really an issue just a sort of request

### ISSUE THREAD

**Issue by FenixChris** [ImTiara/VRCMods#2]
I really love the idea of this mod but it just has one problem that if fixed it would be the exact mod I would like to have, basically what I'm trying to say is that there should be a way to change the text to whatever you want it to say it would be really helpful to learn certain emotions with avatars, now it won't be perfect say like a mod that would give you a little mirror like view of your avatars face in one of the corners of the hud but it would be very nice to have something, and I'm also sorry if there's actually a place for requests I just made an account for github just to tell you this since I couldn't find you on the discord moding group

**Comment by ImTiara** [comment]
Hi, I assume you are talking about GestureIndicator.
I designed this mod to aid with the unreliable finger tracking Index Controllers can have sometimes and thats why its only displaying "Point" or "Hand Open" etc to verify that you are doing the correct gesture. At the moment i sadly have no further plans on expanding this mod.

And you did the right thing by writing this request here so its all good:)
