### ISSUE TITLE
[gesture indicator] allow user to only use icon.

### ISSUE THREAD

**Issue by jll123567** [ImTiara/VRCMods#4]
Would you mind allowing the mod to either just show text, just show icons, or both? I know some users would like to just use the icons without text.

Thanks for reading this by the way.

**Comment by ImTiara** [comment]
Can do, tho i cannot confirm when i got time to implement it.

**Comment by jll123567** [comment]
Thanks! And take your time, I won't explode if it's not done tomorrow lol.

**Comment by syscatFS** [comment]
I added this as a feature in my PR
