### ISSUE TITLE
Drag Fix does not works in VRC build 1172 both PC and VR, but there has no error message inside log.

### ISSUE THREAD

**Issue by VRC-INYO** [ImTiara/VRCMods#5]
Using either ML 0.5.3 or 0.5.4 get same result.

**Comment by ImTiara** [comment]
Hi.
It appears that VRChat has made changes to their input system (I suspect it was the
"`Fixed an issue where the VRChat UI could react when the mouse cursor was not over the window`")
Will try to find a fix asap.

**Comment by VRC-INYO** [comment]
Works great now ! thx for the fix.
